CREATE SEQUENCE HIBERNATE_SEQUENCE;
  
CREATE TABLE LIVRO (
  ID bigint auto_increment,
  NOME VARCHAR(250) NOT NULL,
  QUANTIDADE_PAGINAS INT NOT NULL,
  AUTOR_ID INT NOT NULL
);

CREATE TABLE AUTOR (
  ID bigint auto_increment,
  NOME VARCHAR(250) NOT NULL
);

CREATE TABLE LOGIN (
  USERNAME VARCHAR(250) NOT NULL,
  PASSWORD VARCHAR(250) NOT NULL
);

CREATE TABLE ROLE (
  ID bigint auto_increment,
  ROLE VARCHAR(250) NOT NULL
);

CREATE TABLE LOGIN_ROLES (
  ROLES_ID INT NOT NULL,
  LOGIN_USERNAME VARCHAR(250) NOT NULL
);


